# Generated by Django 4.0.6 on 2022-07-24 08:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('Graphic Des', 'Graphic Designing')], max_length=100)),
                ('project_name', models.CharField(max_length=50)),
                ('project_image', models.ImageField(upload_to='', validators=[django.core.validators.validate_image_file_extension])),
                ('project_desc', models.CharField(max_length=150)),
                ('project_link', models.URLField()),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-time'],
            },
        ),
    ]
