# Generated by Django 4.0.6 on 2022-07-24 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_portfolio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='project_link',
        ),
    ]
