# Generated by Django 4.0.6 on 2022-07-24 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_portfolio_project_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='service_type',
            field=models.CharField(choices=[('Data Analysis', 'Data Analysis'), ('Graphic Des', 'Graphic Designing'), ('Marketing', 'Marketing'), ('SEO', 'SEO'), ('Tech solutions', 'Tech solutions'), ('Web development', 'Web development')], max_length=100),
        ),
    ]
