# Generated by Django 3.2.10 on 2022-08-31 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_portfolio_service_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='project_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='service_type',
            field=models.CharField(choices=[('SEO', 'SEO'), ('Data Analysis', 'Data Analysis'), ('Graphic Designing', 'Graphic Designing'), ('Web development', 'Web development'), ('Tech solutions', 'Tech solutions'), ('Marketing', 'Marketing')], max_length=100),
        ),
    ]
