# Generated by Django 3.2.10 on 2022-08-31 10:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20220831_1454'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='Team-Images', validators=[django.core.validators.validate_image_file_extension])),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=150)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=50)),
                ('client_message', models.TextField()),
                ('testimonial_image', models.ImageField(upload_to='Testimonial-Images', validators=[django.core.validators.validate_image_file_extension])),
                ('published_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-published_at'],
            },
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='project_image',
            field=models.ImageField(upload_to='Porfolio-Images', validators=[django.core.validators.validate_image_file_extension]),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='service_type',
            field=models.CharField(choices=[('Data Analysis', 'Data Analysis'), ('Marketing', 'Marketing'), ('Tech solutions', 'Tech solutions'), ('Web development', 'Web development'), ('SEO', 'SEO'), ('Graphic Designing', 'Graphic Designing')], max_length=100),
        ),
    ]
